services:
  # ===== Main Dashboard =====
  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    container_name: websec-dashboard
    ports:
      - "80:80"
    volumes:
      - ./dashboard:/usr/share/nginx/html
    depends_on:
      - php-server
    networks:
      - websec-network
    restart: unless-stopped

  # ===== PHP 서버 =====
  php-server:
    build:
      context: ./servers/php-server
      dockerfile: Dockerfile.local
    container_name: websec-php
    ports:
      - "8080:80"
    networks:
      - websec-network
    restart: unless-stopped

  # ===== Node.js 서버 =====
  nodejs-server:
    build:
      context: ./servers/nodejs-server
      dockerfile: Dockerfile
    container_name: websec-nodejs
    ports:
      - "3000:3000"
    networks:
      - websec-network
    restart: unless-stopped

  # ===== Python 서버 =====
  python-server:
    build:
      context: ./servers/python-server
      dockerfile: Dockerfile
    container_name: websec-python
    ports:
      - "5000:5000"
    networks:
      - websec-network
    restart: unless-stopped

  # ===== Java 서버 =====
  java-server:
     build:
       context: ./servers/java-server
       dockerfile: Dockerfile
     container_name: websec-java
     ports:
       - "8081:8080"
     networks:
       - websec-network
     restart: unless-stopped

  # ===== Go 서버 (빌드 오류로 임시 비활성화) =====
  go-server:
     build:
       context: ./servers/go-server
       dockerfile: Dockerfile
     container_name: websec-go
     ports:
       - "8082:8080"
     networks:
       - websec-network
     restart: unless-stopped

# ===== 네트워크 정의 =====
networks:
  websec-network:
    driver: bridge
